apiVersion: v1
kind: Service
metadata:
  name: spring-email-service
spec:
  selector:
    app: spring-email-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
